services:
  kinch-code-cli:
    image: kinch-code-cli:latest
    build: .
    env_file:
      - .env
    volumes:
      # Mounts the codebase you want to analyze into the container
      - "${CODE_TO_ANALYZE_PATH:-.}:/app/code-to-analyze"
      # Mounts your config/cache directory to make it persistent across runs
      - "${CONFIG_PATH:-~/.claude-code}:/root/.claude-code"
    # These two lines are essential for an interactive CLI session
    stdin_open: true # Keeps the input stream open (like -i)
    tty: true        # Allocates a pseudo-terminal (like -t)